[package]
name = "deno_winit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.29.10"

[lib]
name = "winit"
crate-type = ["cdylib"]
path = "./src/lib.rs"
